### PR TITLE
Update version to 1.0.7

### PR DESCRIPTION
**Pull request by akhilerm**

### CODE REVIEW

**Comment by akhilerm** [comment]
cc: @lunakoly

**Comment by lunakoly** [comment]
We can try to reduce the list of IDE versions to check (`pluginVerifierIdeVersions`). Will the step still fail if we remove a version or two?

Also, maybe I should update the plugin code to the latest template configuration, where this property isn't used anymore and the versions are picked automatically (maybe they do it more optimally than we do)

**Comment by akhilerm** [comment]
If we remove versions from `pluginVerifierIdeVersions`, will the plugin become incompatible with older versions? Because the older 2021.* versions still have a significant user base.

**Comment by akhilerm** [comment]
Still there are some issues in the verifier step. I am not able to identify the problem. @lunakoly Can you help here?

**Comment by lunakoly** [comment]
> If we remove versions from pluginVerifierIdeVersions, will the plugin become incompatible with older versions? Because the older 2021.* versions still have a significant user base.

I think, if we remove some entries from `pluginVerifierIdeVersions`, but leave `platformVersion` unchanged, then nothing would stop working (at least, immediately).

Thank you for the attempt, I will look into the problem today.

**Comment by akhilerm** [comment]
@lunakoly Can this PR be merged? Or are we waiting for #16

**Comment by lunakoly** [comment]
Yes, I wanted to deal with that PR first. I'll have a look at it today or during the weekend

**Comment by lunakoly** [comment]
@akhilerm, I have merged a PR that copies the up-to-date project configuration from the original IntelliJ Plugin Template (#17), as well as another PR that fixes `No space left on device` (#18). Initially I attempted to only check 3 IDE versions, but it didn't solve the problem. `https://github.com/jlumbroso/free-disk-space` did. When called right before verification, it cleans 20gb+ of some junk (I stumbled upon this fix while searching the IntelliJ Platform slack).

Also, the second PR allows the Copy Line Link action to be executed before the indexes have been built, and bumps up the plugin version to 1.0.7

**Comment by lunakoly** [comment]
Also now we don't have an upper bound for IDE versions, so we won't need to update the plugin manually every time. The plugin is simple enough to assume it will continue working properly (IntelliJ Marketplace does warn me about the use of deprecated API, and it looks like they have pretty long deprecation cycles).

**Comment by akhilerm** [comment]
Not having an upper bound helps with frequent updates that we have to make every quarter

**Pull request closed without merging**
