### PR TITLE
add support for ssh remote

### PR DESCRIPTION
**Pull request by akhilerm**
- support parsing ssh remote URLs

Signed-off-by: Akhil Mohan <akhilerm@gmail.com>

### CODE REVIEW

**Comment by akhilerm** [comment]
I still dont know how to test the plugin, it would be great if you could help with that.

**Comment by lunakoly** [comment]
Hi! Thank you for the changes, but, please, also do the following:

- run the `Run Test` IntelliJ config to ensure the code meets the style guide (gradle `:check` task)
  - if it doesn't, please, refactor the code according to the style guide
- increase the `pluginVersion=1.0.3` value to, for example, 1.0.4.
- add the description about the change to the changelog file
  - no need to specify a version here, just add the "Added" section to the `[Unreleased]` and describe the change itself
  - the changelog will be updated automatically by the GitHub `Release` action when a new release draft is approved

Before accepting your pull request the GitHub `Build` action will be run. This action will verify the plugin works for the requested IJ versions.

And also, please, refactor the `removeProtocol` function in a declarative fashion:
```kotlin
fun String.removeProtocol(): String {
    val protocolSeparator = when {
        startsWith(SSH_URL_IDENTIFIER) -> GIT_PROTOCOL_SEPARATOR
        else -> HTTPS_PROTOCOL_SEPARATOR
    }

    val index = this.indexOf(protocolSeparator)

    return if (index != -1) {
        substring(index + protocolSeparator.length)
    } else {
        this
    }
}
```

**Comment by lunakoly** [comment]
Also, please, squash the changes into a single commit and capitalize the first word, and append an emoji prefix (for example, 🔥) so that the commit looks consistent with the previous ones :)

**Comment by akhilerm** [comment]
@lunakoly Updated the PR with the requested changes

**Comment by akhilerm** [comment]
Would be nice to have the above information in a `CONTRIBUTING.md` file.

Also, how long does it take for a newer version to be available in the marketplace after the github release has been made.

**Comment by lunakoly** [comment]
> Would be nice to have the above information in a CONTRIBUTING.md file.

Maybe you're right, but since the project is based on the [general IJ plugin template](https://github.com/JetBrains/intellij-platform-plugin-template), I assume it's better to go there for the maintenance details.

> Also, how long does it take for a newer version to be available in the marketplace after the github release has been made.

This usually happens within 2 business days.

**Pull request merged**
