### PR TITLE
🔥 Add Bitbucket URL support

### PR DESCRIPTION
**Pull request by akhilerm**
add support for generating links for remotes that use bitbucket

### CODE REVIEW

**Comment by lunakoly** [comment]
Don't forget to update the plugin version and leave a message in the changelog :)

**Comment by akhilerm** [comment]
> @akhilerm Don't forget to update the plugin version and leave a message in the changelog :)

Done.

**Comment by akhilerm** [comment]
@lunakoly Can you also trigger a new release with the bitbucket support?

**Comment by lunakoly** [comment]
Sure thing, thanks for the reminder :)

**Comment by akhilerm** [comment]
Can we also have the `Getting Started` updated with support for Bitbucket also in https://plugins.jetbrains.com/plugin/17287-quick-link.

**Pull request merged**
